### ISSUE TITLE
toUpperCase error

### ISSUE THREAD

**Issue by n0ldor** [rborn/TaffyDb4Ti#3]
Hi i try to use taffy in my titanium project but when i create my db it shows an error with toUpperCase.

I only use this and in androir and browser shows error:

var taffy = require('/taffydb4ti').taffy;

var friends = new taffy([
    {"id":1,"gender":"M","first":"John","last":"Smith","city":"Seattle, WA","status":"Active"},
    {"id":2,"gender":"F","first":"Kelly","last":"Ruth","city":"Dallas, TX","status":"Active"},
    {"id":3,"gender":"M","first":"Jeff","last":"Stevenson","city":"Washington, D.C.","status":"Active"},
    {"id":4,"gender":"F","first":"Jennifer","last":"Gill","city":"Seattle, WA","status":"Active"}]);

In android the error is 
Exception occurred at taffydb4ti.js:1882: Uncaught TypeError: Object [object Object],[object Object],[object Object],[object Object] has no method 'toUpperCase'

Thanks

**Comment by rborn** [comment]
You are trying to initialise the db in the incorrect way. Please read again the [How-to](https://github.com/rborn/TaffyDb4Ti#how-to) :)

So basically you need to create a store, then to insert the data.

**Comment by n0ldor** [comment]
ok now with this i can start a db and insert and works fine but i don't know how can i load a db in a file. I try to load a js file and never load the array inside it.

var taffy = require('/taffydb4ti').taffy;
var my_db = new taffy('my_db_store_name');
my_db.insert({my_value:'first'});
my_db.insert({my_value:'second'});
my_db.save();

**Comment by rborn** [comment]
You need to have the data from that file already parsed as an object.
The best way is to do something like this:

file data.js

```
exports = [
{"id":1,"gender":"M","first":"John","last":"Smith","city":"Seattle, WA","status":"Active"},
{"id":2,"gender":"F","first":"Kelly","last":"Ruth","city":"Dallas, TX","status":"Active"},
{"id":3,"gender":"M","first":"Jeff","last":"Stevenson","city":"Washington, D.C.","status":"Active"},
{"id":4,"gender":"F","first":"Jennifer","last":"Gill","city":"Seattle, WA","status":"Active"}];
```

then in the file you are inserting the data

```
var my_data = require('data.js');

var taffy = require('/taffydb4ti').taffy;
var my_db = new taffy('my_db_store_name');
my_db.insert(my_data);
my_db.save();
```

PS. code not tested :)
